### ISSUE TITLE
 Error Message : Syntax error in regexp pattern near index 15:    (?<!\{[01]{1})}

### ISSUE THREAD

**Issue by mwshubham** [paypal/merchant-sdk-java#28]
Here is my log can please help why its not working in android 

````
E: Error Message : Syntax error in regexp pattern near index 15:
   (?<!\{[01]{1})}
                  ^
W: java.util.regex.PatternSyntaxException: Syntax error in regexp pattern near index 15:
W: (?<!\{[01]{1})}
W:                ^
W:     at java.util.regex.Pattern.compileImpl(Native Method)
W:     at java.util.regex.Pattern.compile(Pattern.java:407)
W:     at java.util.regex.Pattern.<init>(Pattern.java:390)
W:     at java.util.regex.Pattern.compile(Pattern.java:381)
W:     at java.lang.String.replaceAll(String.java:1774)
W:     at com.paypal.core.soap.MerchantAPICallPreHandler.processPayLoadForFormatting(MerchantAPICallPreHandler.java:466)
W:     at com.paypal.core.soap.MerchantAPICallPreHandler.getPayLoadUsingSOAPHeader(MerchantAPICallPreHandler.java:447)
W:     at com.paypal.core.soap.MerchantAPICallPreHandler.getPayLoad(MerchantAPICallPreHandler.java:317)
W:     at com.paypal.core.BaseService.call(BaseService.java:264)
W:     at urn.ebay.api.PayPalAPI.PayPalAPIInterfaceServiceService.setExpressCheckout(PayPalAPIInterfaceServiceService.java:2196)
W:     at urn.ebay.api.PayPalAPI.PayPalAPIInterfaceServiceService.setExpressCheckout(PayPalAPIInterfaceServiceService.java:2148)
W:     at com.webkul.mobikul.Checkout.setExpressCheckout(Checkout.java:1812)
W:     at com.webkul.mobikul.Checkout$15.onClick(Checkout.java:1494)
````

**Comment by pp-randy** [comment]
@mwshubham the syntax error aside.  

What types of payments are you attempting to make?  

We have some offerings that might be better suited for Android https://developer.paypal.com/docs/integration/mobile/mobile-sdk-overview/

**Comment by mwshubham** [comment]
Closing this issue as similar one is found https://github.com/paypal/merchant-sdk-java/issues/27

help me on this https://github.com/paypal/PayPal-Android-SDK/issues/259
