### ISSUE TITLE
com.paypal.sdk.core.APICallerBase.getEndpointUrl(Unknown Source)

### ISSUE THREAD

**Issue by phillixzk** [paypal/merchant-sdk-java#34]
Merchant is encountering with below error for some of his DoRT API calls (most of DoRT API succeeded). Could you please give any suggestion on the investigation ?

java.lang.NullPointerException
    at com.paypal.sdk.core.APICallerBase.getEndpointUrl(Unknown Source)
    at com.paypal.sdk.core.nvp.NVPAPICaller.setupConnection(Unknown Source)
    at com.paypal.sdk.services.NVPCallerServices.setAPIProfile(Unknown Source)

**Comment by jaypatel512** [comment]
Can you please add the versions they are using for merchant-sdk-java ?

And are they seeing this in live or sandbox ?

**Comment by jaypatel512** [comment]
Closing this issue based on inactivity. Please re-open if you are still facing this issue.
