### ISSUE TITLE
FinancingMonthlyPayment no return currencyID

### ISSUE THREAD

**Issue by felipegirotti** [paypal/merchant-sdk-java#39]
In cases that the field `FinancingMonthlyPayment`is returned, the value currencyId is empty,
That throw the exception: 
```
java.lang.IllegalArgumentException: 
	at urn.ebay.apis.eBLBaseComponents.CurrencyCodeType.fromValue(CurrencyCodeType.java:461) ~[merchantsdk-2.14.117.jar!/:na]
	at urn.ebay.apis.CoreComponentTypes.BasicAmountType.<init>(BasicAmountType.java:145) ~[merchantsdk-2.14.117.jar!/:na]
	at urn.ebay.apis.eBLBaseComponents.PaymentInfoType.<init>(PaymentInfoType.java:1101) ~[merchantsdk-2.14.117.jar!/:na]
	at urn.ebay.apis.eBLBaseComponents.GetExpressCheckoutDetailsResponseDetailsType.<init>(GetExpressCheckoutDetailsResponseDetailsType.java:737) ~[merchantsdk-2.14.117.jar!/:na]
	at urn.ebay.api.PayPalAPI.GetExpressCheckoutDetailsResponseType.<init>(GetExpressCheckoutDetailsResponseType.java:77) ~[merchantsdk-2.14.117.jar!/:na]
	at urn.ebay.api.PayPalAPI.PayPalAPIInterfaceServiceService.getExpressCheckoutDetails(PayPalAPIInterfaceServiceService.java:2347) ~[merchantsdk-2.14.117.jar!/:na]
	at urn.ebay.api.PayPalAPI.PayPalAPIInterfaceServiceService.getExpressCheckoutDetails(PayPalAPIInterfaceServiceService.java:2294) ~[merchantsdk-2.14.117.jar!/:na]
```

The part response:

```
<PaymentInfo xsi:type="ebl:PaymentInfoType">
               <TransactionID />
               <ParentTransactionID xsi:type="ebl:TransactionId" />
               <ReceiptID />
               <TransactionType xsi:type="ebl:PaymentTransactionCodeType">none</TransactionType>
               <PaymentType xsi:type="ebl:PaymentCodeType">none</PaymentType>
               <FinancingMonthlyPayment xsi:type="cc:BasicAmountType" currencyID="">154.16</FinancingMonthlyPayment>
               <FinancingTerm xsi:type="xs:string">1</FinancingTerm>
               <IsFinancing xsi:type="xs:string">true</IsFinancing>
               <ExchangeRate xsi:type="xs:string" />
               <PaymentStatus xsi:type="ebl:PaymentStatusCodeType">None</PaymentStatus>
               <PendingReason xsi:type="ebl:PendingStatusCodeType">none</PendingReason>
               <ReasonCode xsi:type="ebl:ReversalReasonCodeType">none</ReasonCode>
               <SellerDetails xsi:type="ebl:SellerDetailsType" />
            </PaymentInfo>
```

**Comment by pp-randy** [comment]
@felipegirotti

Can you confirm either: 
This is an issue with the response XML not having the currency? 
This is an issue with the SDK not populating the currency in the request XML?

If it is an issue with the response XML, can would you also provide a correlation id? 

Internal Tracking: PPPLMER-21604

**Comment by felipegirotti** [comment]
@pp-randy sorry for delay,

This is issue is response XML not having the currency, the currency is empty.

The correlation id: fb046d1a58e5b
Date: November 15th 2016, 23:45:05

But in doc online for this field says: "**It includes no currency symbol**"

https://developer.paypal.com/docs/classic/api/merchant/GetExpressCheckoutDetails_API_Operation_SOAP/

**Comment by pp-randy** [comment]
The SDK needs to be updated to API version 123 or higher to support installments. 
New internal tracking: BTDXCLTS-436
